server:
  port: 10020
cache: ribbon

default:
  user: root
  password: 123456

spring:
  application:
    name: im-client
  profiles:
    include: consul

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

